### ISSUE TITLE
Tokio Runtime & Lua API Calls

### ISSUE THREAD

**Issue by jaw-sh** [khvzak/haproxy-api-rs#2]
I am trying to access Scylla in my API, which necessarily requires Tokio.  While #[tokio::main] can be added just fine on the library (and Scylla can be accessed fine from the main function when the library loads), it cannot be accessed in subsequent calls from any functions which are invoked from the Lua runtime. I have tested filters, actions, and functions for this.

Trying to call Tokio functions from the haproxy lua runtime throws this error,
`thread '<unnamed>' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime',`

And trying to create or otherwise block_on with Tokio in an haproxy lua runtime throws this error,
`panicked at 'OS can't spawn worker thread: Resource temporarily unavailable (os error 11)'`

It's entirely possible I just don't know what I'm doing, but is there any way to make calls in a Tokio runtime when called by the haproxy?

**Comment by khvzak** [comment]
You can force enter to Tokio runtime in a Lua module, for example:
```rust
static RT: Lazy<tokio::runtime::Runtime> = Lazy::new(|| {
    std::thread::spawn::<_, ()>(|| RT.block_on(futures::future::pending()));
    tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .unwrap()
});

static GUARD: Lazy<tokio::runtime::EnterGuard> = Lazy::new(|| RT.enter());

#[mlua::lua_module]
fn my_module(lua: &Lua) -> Result<Table> {
    let _guard = &*GUARD;
   ... code ...
}
```

**Comment by khvzak** [comment]
> panicked at `'OS can't spawn worker thread: Resource temporarily unavailable (os error 11)'`

You probably need to enable [`insecure-fork-wanted`](http://docs.haproxy.org/2.7/configuration.html#insecure-fork-wanted) option in HAProxy

**Comment by jaw-sh** [comment]
Brilliant @ `insecure-fork-wanted`. I am now able to run Scylla commands within a Runtime block_on, as if it were a normal binary.
